site_name: taxburst docs
repo_url: https://github.com/taxburst/taxburst
docs_dir: ./doc/

nav:
- Home: README.md
- Quickstart: quickstart.md
- Command line docs: command-line.md
- Developer Information: developer.md

markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - attr_list
  - admonition

plugins:
  - search

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
