rule all:
    input:
        'outputs/SRR606249.x.podar.tax.html',
        'outputs/small.tax.html',

rule build_example:
    input:
        '../examples/{name}.csv',
    output:
        'outputs/{name}.html',
    shell: """
        ../build-html.py {input} -o {output}
 """
