rule all:
    input:
        "../doc/examples/SRR11125891.summarized.html",
        "../doc/examples/SRR11125891.tax_annotate.html",
        "../doc/examples/SRR11125891.SingleM.html",
        "../doc/examples/SRR11125891.krona.html",

rule csv_sum:
    input: "SRR11125891.summarized.csv",
    output: "../doc/examples/SRR11125891.summarized.html",
    shell: """
        taxburst {input} -o {output}
    """

rule tax_ann:
    input: "SRR11125891.t0.gather.with-lineages.csv"
    output: "../doc/examples/SRR11125891.tax_annotate.html",
    shell: """
        taxburst {input} -o {output} -F tax_annotate
    """

rule tsv_singlem:
    input: "SRR11125891.singleM.profile.tsv",
    output: "../doc/examples/SRR11125891.SingleM.html",
    shell: """
        taxburst {input} -o {output} -F SingleM
    """


rule tsv_krona:
    input: "SRR11125891.krona.tsv",
    output: "../doc/examples/SRR11125891.krona.html",
    shell: """
        taxburst -F krona {input} -o {output}
    """
