name: build and deploy mkdocs to github pages

permissions:
  pages: write
  contents: write

on:
  push:
    branches:
      - main
      - fix_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
